"""empty message

Revision ID: f40d587859c0
Revises: b62d71b55af9
Create Date: 2021-03-01 23:11:33.486727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40d587859c0'
down_revision = 'b62d71b55af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('birth', table_name='character')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('birth', 'character', ['birth'], unique=True)
    # ### end Alembic commands ###
